//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcTesting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class activities
    {
        public int A_ID { get; set; }
        public bool review { get; set; }
        public bool Input { get; set; }
        public bool Decision { get; set; }
        public Nullable<System.DateTime> Check_In { get; set; }
        public Nullable<System.DateTime> Check_Out { get; set; }
        public Nullable<System.DateTime> Due_Date { get; set; }
    
        public virtual Emps Emps { get; set; }
        public virtual Emps Emps1 { get; set; }
        public virtual Processes Processes { get; set; }
    }
}
