//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcTesting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Depts
    {
        public Depts()
        {
            this.Emps = new HashSet<Emps>();
        }
    
        public int Dept_ID { get; set; }
        public string Dept_Name { get; set; }
    
        public virtual ICollection<Emps> Emps { get; set; }
    }
}
