//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcTesting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emps
    {
        public Emps()
        {
            this.activities = new HashSet<activities>();
            this.activities1 = new HashSet<activities>();
        }
    
        public int E_ID { get; set; }
        public string E_Name { get; set; }
        public string E_Desg { get; set; }
    
        public virtual ICollection<activities> activities { get; set; }
        public virtual ICollection<activities> activities1 { get; set; }
        public virtual Depts Depts { get; set; }
    }
}
