//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcTesting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Processes
    {
        public Processes()
        {
            this.activities = new HashSet<activities>();
        }
    
        public int Process_ID { get; set; }
        public string Process_Name { get; set; }
    
        public virtual ICollection<activities> activities { get; set; }
    }
}
