//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFTest1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {

        public int ActivityId;
        public bool Input { get; set; }
        public int FormId { get; set; }
        public int RoleId { get; set; }
        public System.DateTime DueDate { get; set; }
        public Nullable<int> BackState { get; set; }
    }
}
