//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFTest1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddmissionInstance
    {
        public int FormId { get; set; }
        public int AddmissionId { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> ApproveBy { get; set; }
        public string Remark { get; set; }
        public Nullable<bool> Approve { get; set; }
    
        public virtual Form Form { get; set; }
    }
}
