//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFTest1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Form_Divsion
    {
        public Form_Divsion()
        {
            this.Moniterings = new HashSet<Monitering>();
            this.Pendings = new HashSet<Pending>();
        }
    
        public int FD_ID { get; set; }
        public int FormId { get; set; }
        public int RoleId { get; set; }
    
        public virtual Form Form { get; set; }
        public virtual webpages_Roles webpages_Roles { get; set; }
        public virtual ICollection<Monitering> Moniterings { get; set; }
        public virtual ICollection<Pending> Pendings { get; set; }
    }
}
