//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFTest1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Form
    {
        public Form()
        {
            this.AddmissionInstances = new HashSet<AddmissionInstance>();
            this.Form_Divsion = new HashSet<Form_Divsion>();
            this.Moniterings = new HashSet<Monitering>();
            this.Pendings = new HashSet<Pending>();
        }
    
        public int formID { get; set; }
        public string formName { get; set; }
    
        public virtual ICollection<AddmissionInstance> AddmissionInstances { get; set; }
        public virtual ICollection<Form_Divsion> Form_Divsion { get; set; }
        public virtual ICollection<Monitering> Moniterings { get; set; }
        public virtual ICollection<Pending> Pendings { get; set; }
    }
}
