//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFTest1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pending
    {
        public int PId { get; set; }
        public int FD_ID { get; set; }
        public int InstanceId { get; set; }
        public int FormId { get; set; }
    
        public virtual Form Form { get; set; }
        public virtual Form_Divsion Form_Divsion { get; set; }
    }
}
