//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFTest2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public int A_ID { get; set; }
        public int Process_Id { get; set; }
        public int Role_Id { get; set; }
        public bool input { get; set; }
        public bool Review { get; set; }
        public bool Decision { get; set; }
    
        public virtual Process Process { get; set; }
    }
}
