//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFTest2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Field
    {
        public int Field_Id { get; set; }
        public int Form_Id { get; set; }
        public int Role_Id { get; set; }
        public string Labels { get; set; }
        public string Fields { get; set; }
    
        public virtual Form Form { get; set; }
        public virtual Role Role { get; set; }
    }
}
