//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFTest2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Form
    {
        public Form()
        {
            this.Fields = new HashSet<Field>();
            this.Processes = new HashSet<Process>();
        }
    
        public int Form_Id { get; set; }
        public string Form_Name { get; set; }
    
        public virtual ICollection<Field> Fields { get; set; }
        public virtual ICollection<Process> Processes { get; set; }
    }
}
