//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFTest2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Process
    {
        public Process()
        {
            this.Activities = new HashSet<Activity>();
        }
    
        public int Process_Id { get; set; }
        public int Form_Id { get; set; }
        public string Proces_Name { get; set; }
    
        public virtual ICollection<Activity> Activities { get; set; }
        public virtual Form Form { get; set; }
    }
}
